fragment CorePostFields on Post {
    createdAt
    date
    excerpt
    id
    subject
    tags
    title
    updatedAt
}

fragment Author on Post {
    author {
        id
        name
    }
}

query GetPosts($skip: Int, $first: Int, $search: String, $tags: [String!]) {
    postsConnection(
        skip: $skip,
        first: $first,
        orderBy: createdAt_DESC,
        where: {
            AND: [
                { OR: [
                    { title_contains: $search },
                    { subject_contains: $search },
                    { slug_contains: $search }
                ] },
                { tags_contains_all: $tags }
            ]
        }
    ) {
        edges {
            cursor
            node {
                ...Author
                ...CorePostFields
            }
        }
        pageInfo {
            hasNextPage
            hasPreviousPage
            startCursor
            endCursor
            pageSize
        }
    }
}

query GetPost($postId: ID!) {
    post(where: { id: $postId }) {
        content {
            html
        }
        ...Author
        ...CorePostFields
    }
}


